theme: jekyll-theme-slate
title: Cougar Chase - Basic JavaScript Game Workshop
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable : true